class DigitalPartsMap
  def self.by_number(number)
    case number
    when 0
        [
          :down_right,
          :left_right,
          :down_left,
          :down_up,
          :not_parts,
          :down_up,
          :down_up,
          :not_parts,
          :down_up,
          :down_up,
          :not_parts,
          :down_up,
          :up_right,
          :left_right,
          :up_left
        ]
    when 1
        [
          :not_parts,
          :not_parts,
          :down_down,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :up_up
        ]
    when 2
        [
          :right_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :down_right,
          :left_right,
          :up_left,
          :down_up,
          :not_parts,
          :not_parts,
          :up_right,
          :left_right,
          :left_left
        ]
    when 3
        [
          :right_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :right_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :right_right,
          :left_right,
          :up_left
        ]
    when 4
        [
          :down_down,
          :not_parts,
          :down_down,
          :down_up,
          :not_parts,
          :down_up,
          :up_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :up_up
        ]
    when 5
        [
          :down_right,
          :left_right,
          :left_left,
          :down_up,
          :not_parts,
          :not_parts,
          :up_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :right_right,
          :left_right,
          :up_left
        ]
    when 6
        [
          :down_right,
          :left_right,
          :left_left,
          :down_up,
          :not_parts,
          :not_parts,
          :down_right,
          :left_right,
          :down_left,
          :down_up,
          :not_parts,
          :down_up,
          :up_right,
          :left_right,
          :up_left
        ]
    when 7
        [
          :right_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :down_up,
          :not_parts,
          :not_parts,
          :up_up
        ]
    when 8
        [
          :down_right,
          :left_right,
          :down_left,
          :down_up,
          :not_parts,
          :down_up,
          :up_right,
          :left_right,
          :down_left,
          :down_up,
          :not_parts,
          :down_up,
          :up_right,
          :left_right,
          :up_left
        ]
    when 9
        [
          :down_right,
          :left_right,
          :down_left,
          :down_up,
          :not_parts,
          :down_up,
          :up_right,
          :left_right,
          :down_left,
          :not_parts,
          :not_parts,
          :down_up,
          :right_right,
          :left_right,
          :up_left
        ]
    else
        []
    end
  end
end
